version: '2'
services:
  ork3app:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
     - 19080:80
    working_dir: /var/www
    volumes:
      - .:/var/www/ork.amtgard.com
      - /var/log/apps/ork.amtgard.com:/var/log
    env_file: .prod.env
    environment:
      - ENVIRONMENT=PROD
    container_name: ork3-php8-app
    networks:
      - ork3-php8-net
      
volumes:
  data-db: {}

networks:
  ork3-php8-net:
