version: '2'
services:
  orkapp:
    build:
      context: ./
      dockerfile: php.Dockerfile
    ports:
     - 18080:80
    working_dir: /var/www
    volumes:
      - ./:/var/www/html/ork/
    env_file: .dev.env
    container_name: ork-app
    networks:
      - orknet
  orkdb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_DATABASE: 'ork'
      # So you don't have to use root, but you can if you like
      MARIADB_USER: 'ork'
      # You can use whatever password you like
      MARIADB_PASSWORD: 'secret'
      # Password for root access
      MARIADB_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '23306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - data-db:/var/lib/mysql
    container_name: ork-db
    networks:
      - orknet

volumes:
  data-db: {}

networks:
  orknet:
